version: '3'
networks:
  traefik-public:
    external: true
  internal:

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - internal
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     restart: always
     volumes:
       - wordpress_data:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
        - traefik-public
        - internal
     deploy:
       labels:
         - traefik.enable=true
         - traefik.docker.network=traefik-public
         - traefik.constraint-label=traefik-public
         - traefik.http.routers.${TRAEFIK_ROUTER}-http.rule=Host(`${DOMAIN}`)
         - traefik.http.routers.${TRAEFIK_ROUTER}-http.entrypoints=http
         - traefik.http.routers.${TRAEFIK_ROUTER}-http.middlewares=https-redirect
         - traefik.http.routers.${TRAEFIK_ROUTER}-https.rule=Host(`${DOMAIN}`)
         - traefik.http.routers.${TRAEFIK_ROUTER}-https.entrypoints=https
         - traefik.http.routers.${TRAEFIK_ROUTER}-https.tls=true
         - traefik.http.routers.${TRAEFIK_ROUTER}-https.tls.certresolver=le
         - traefik.http.services.${TRAEFIK_ROUTER}.loadbalancer.server.port=80

volumes:
    db_data:
    wordpress_data:
